config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      put 'shipped'
      put 'returned'
      put 'cancelled'
    end
  end
  get 'pages/home'
  get 'pages/controlpanel'
  get 'pages/shipping_calculator'

  devise_for :users

  root 'pages#home'

end

app/models/config_panel.rb
class ConfigPanel < ActiveRecord::Base
  def self.get_cp
    if ConfigPanel.all.count > 0
      return ConfigPanel.first
    else
      cp = ConfigPanel.new
      cp.save!
      return cp
    end
  end

  def has_usps?
    return false
  end

  def has_ups?
    return false
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  def self.all_new
    return Order.all.where(shipped: false, returned: false, cancelled: false ).sort_by &:order_datetime
  end

  def self.all_shipped_returned
    return Order.all.where(shipped: true )
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save :is_first_user?

  def self.no_users_exist?
    return true if User.all.count == 0
    return false
  end

  def is_first_user?
    self.acct_type = 1 if User.all.count == 0
    ConfigPanel.get_cp
  end

  def is_admin?
    return true if self.acct_type == 1
    return false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name]
    devise_parameter_sanitizer.for(:account_update) << [:name]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_permissions
  before_action :set_order, only: [:show, :edit, :update, :destroy, :shipped, :returned, :cancelled]
  before_action :demo_check, only: [:create, :update, :destroy, :shipped, :returned, :cancelled]

  def shipped
    @order.shipped = true
    @order.shipper_id = current_user.id
    @order.shipped_datetime = DateTime.now
    @order.save!
    redirect_to orders_path
  end

  def returned
    @order.returned = true
    @order.returner_id = current_user.id
    @order.return_datetime = DateTime.now
    @order.save!
    redirect_to orders_path
  end

  def cancelled
    @order.cancelled = true
    @order.cancelled_id = current_user.id
    @order.save!
    redirect_to orders_path
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.order_datetime = DateTime.now

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    return redirect_to root_path
    #@order.destroy
    #respond_to do |format|
    #  format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :order_amt, :price, :shipping_amt, :tax, :final_price, :order_datetime, :desc, :shipping_code, :shipping_type, :address, :address2, :city, :zipcode, :shipping_notes, :return_notes, :country)
    end

    def check_permissions
      return redirect_to root_path, notice: "Please log in" if not current_user
    end

    def demo_check
      redirect_to orders_path, notice: "Not allowed in Demo Mode" if ENV['DEMO_MODE']
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if ENV['DEMO_MODE']
      @orders = Order.all
    end

    return redirect_to orders_path if current_user
  end

  def controlpanel
    return redirect_to root_path, notice: "Please log in" if not current_user

    return redirect_to root_path, notice: "Only Admin users can access" if not current_user.is_admin?

  end

  def shipping_calculator
    return redirect_to root_path, notice: "Please log in" if not current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <row>
    <div class="col-sm-8 col-xs-12 text-muted">Simple Order System</div>
    <div class="col-sm-4 col-xs-12 text-muted pull-really-right">Copyright © 2016 John B. Wyatt IV</div>
  </row>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Simple Order System</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if false %>
      <ul class="nav navbar-nav">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%=current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "#{current_user.email}", pages_home_path  %></li>
            <li></i><%= link_to "Settings", edit_user_registration_path  %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to"Sign Up", new_user_registration_path  %></li>
        <li><%= link_to "Sign In", new_user_session_path  %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Order System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

</head>
<body data-no-turbolink="true">

  <%= render "layouts/header" %>
  <div class="container">

  <% if ENV['DEMO_MODE'] %>
    <div class="alert alert-info fade-in">
        You are in Demo Mode. Please email johnwyatt@wyatttechcourses.com for licensing information. The app sorts orders by date and displays priority colors for 7 days and 14 days. You can track employees by having them register an account and clicking Shipped? to record when they ship an order. They can also record refunds and notes.
    </div>
  <% end %>

  <% flash.each do |type, message| %>
    <div class="alert alert-info fade-in">
      <button class="close" data-dismiss="alert">x</button>
      <%= message %>
    </div>
  <% end %>

  <%= yield %>

  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :order_amt %>
    <%= f.input :price %>
    <%= f.input :shipping_amt %>
    <%= f.input :tax %>
    <%= f.input :final_price, placeholder: "ex. $13.97 All number fields are strings of text to easily handle different currencies." %>
    <%= f.input :order_datetime %>
    <%= f.input :desc, as: :text, label: 'Description' %>
    <%= f.input :shipping_code, label: 'Shipping Tracking Code' %>
    <%= f.input :shipping_type, label: 'UPS (use 1 ) or USPS (use 2 )?' %>
    <%= f.input :address %>
    <%= f.input :address2 %>
    <%= f.input :city %>
    <%= f.input :zipcode, label: 'Postal Code (Zipcode)' %>
    <%= f.input :shipping_notes, as: :text  %>
    <%= f.input :return_notes, as: :text  %>
    <%= f.input :country, priority: [ "United States", "Canada", "United Kingdom", "Australia", "India" ] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<% if not @orders.all_new.empty? %>

<%= link_to 'New Order', new_order_path, class: "btn btn-default" %>
<br />

<h1>Listing Orders</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Order amt</th>
      <th>Shipping amt</th>
      <th>Final Amt</th>
      <th>Order datetime</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.all_new.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.order_amt %></td>
        <td><%= order.shipping_amt %></td>
        <td><%= order.final_price %></td>
        <td><%= order.order_datetime.strftime("%A-%m-%Y %H:%M") %></td>
        <td><%= order.address %></td>
        <td><%= order.address2 %></td>
        <td><%= order.city %></td>
        <td><%= order.zipcode %></td>
        <td>
        <% if Date.today - 14.days >= order.order_datetime %>
        <span class="label label-danger"><%=   (Date.today - order.order_datetime.to_date).to_i%> Days old!</span>
        <% elsif Date.today - 7.days >= order.order_datetime %>
        <span class="label label-warning"><%=   (Date.today - order.order_datetime.to_date).to_i%> Days old! </span>
        <% end %>
        </td>

        <td><%= order.shipping_code %></td>
        <td><%= order.shipping_type %></td>

        <td><%= link_to 'Show', order, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_order_path(order), class: "btn btn-default" %></td>
        <td><%= link_to 'Shipped?', shipped_order_path(order), method: :put, class: "btn btn-primary" %></td>
        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, cancelled_order_path(order), method: :put, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br >

<% end %>

<% if not @orders.all_shipped_returned.empty? %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Order amt</th>
      <th>Shipping amt</th>
      <th>Final Amt</th>
      <th>Order datetime</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>Shipper</th>
      <th>Returner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.all_shipped_returned.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.order_amt %></td>
        <td><%= order.shipping_amt %></td>
        <td><%= order.final_price %></td>
        <td><%= order.order_datetime %></td>
        <td><%= order.address %></td>
        <td><%= order.address2 %></td>
        <td><%= order.city %></td>
        <td><%= order.zipcode %></td>
        <td><span class="label label-warning"><%= User.find(order.shipper_id).name if order.shipper_id %></span></td>
        <td><span class="label label-warning"><%= User.find(order.returner_id).name if order.returner_id %></span></td>

        <td><%= order.shipping_code %></td>
        <td><%= order.shipping_type %></td>

        <td><%= link_to 'Show', order, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_order_path(order), class: "btn btn-default" %></td>
        <td><%= link_to 'Returned?', returned_order_path(order), class: "btn btn-primary", method: :put %></td>
        <% if current_user.is_admin?%>
        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, cancelled_order_path(order), class: "btn btn-danger", method: :put %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>
<br />
<%= link_to 'Back', orders_path, class: "btn btn-primary" %>

app/views/orders/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Order Amt:</strong>
  <%= @order.order_amt %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Shipping Amt:</strong>
  <%= @order.shipping_amt %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @order.tax %>
</p>

<p>
  <strong>Final price:</strong>
  <%= @order.final_price %>
</p>

<p>
  <strong>Order datetime:</strong>
  <%= @order.order_datetime.strftime("%A-%m-%Y %H:%M") if @order.order_datetime %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @order.desc %>
</p>

<p>
  <strong>Shipping code:</strong>
  <%= @order.shipping_code %>
</p>

<p>
  <strong>Shipping type:</strong>
  <%= @order.shipping_type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @order.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @order.zipcode %>
</p>

<p>
  <strong>Shipping notes:</strong>
  <%= @order.shipping_notes %>
</p>

<p>
  <strong>Return notes:</strong>
  <%= @order.return_notes %>
</p>

<p>
  <strong>Shipper:</strong>
  <span class="label label-warning"><%= User.find(@order.shipper_id).name if @order.shipper_id %></span>
</p>

<p>
  <strong>Returner:</strong>
  <span class="label label-warning"><%= User.find(@order.returner_id).name if @order.returner_id %></span>
</p>

<p>
  <strong>Return datetime:</strong>
  <%= @order.return_datetime.strftime("%A-%m-%Y %H:%M") if @order.return_datetime%>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/controlpanel.html.erb
<%= simple_form_for(@controlpanel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :shipping_country %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pages/home.html.erb
<% if current_user %>
  <%= link_to "Go to Order System", "#", class: "btn btn-primary btn-lg" %>
<% else %>
  <p>Please sign in/register to use the system</p>
<% end %>

<% if ENV['DEMO_MODE'] %>

  <%= link_to 'New Order', new_order_path, class: "btn btn-default" %>

  <br />

  <% if not @orders.all_new.empty? %>

  <h1>Listing Orders</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Order Amt</th>
        <th>Shipping Amt</th>
        <th>Final Amt</th>
        <th>Order datetime</th>
        <th>Address</th>
        <th>Address2</th>
        <th>City</th>
        <th>Zipcode</th>
        <th>Priority</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.all_new.each do |order| %>
        <tr>
          <td><%= order.name %></td>
          <td><%= order.order_amt %></td>
          <td><%= order.shipping_amt %></td>
          <td><%= order.final_price %></td>
          <td><%= order.order_datetime.strftime("%A-%m-%Y %H:%M") %></td>
          <td><%= order.address %></td>
          <td><%= order.address2 %></td>
          <td><%= order.city %></td>
          <td><%= order.zipcode %></td>
          <td>
          <% if Date.today - 14.days >= order.order_datetime %>
          <span class="label label-danger"><%=   (Date.today - order.order_datetime.to_date).to_i%> Days old!</span>
          <% elsif Date.today - 7.days >= order.order_datetime %>
          <span class="label label-warning"><%=   (Date.today - order.order_datetime.to_date).to_i%> Days old! </span>
          <% end %>
          </td>

          <td><%= order.shipping_code %></td>
          <td><%= order.shipping_type %></td>

          <td><%= link_to 'Show', order, class: "btn btn-default" %></td>
          <td><%= link_to 'Edit', edit_order_path(order), class: "btn btn-default" %></td>
          <td><%= link_to 'Shipped?', shipped_order_path(order), method: :put, class: "btn btn-primary" %></td>
          <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, cancelled_order_path(order), method: :put, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br >

  <% end %>

  <% if not @orders.all_shipped_returned.empty? %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Order amt</th>
        <th>Shipping amt</th>
        <th>Final Amt</th>
        <th>Order datetime</th>
        <th>Address</th>
        <th>Address2</th>
        <th>City</th>
        <th>Zipcode</th>
        <th>Shipper</th>
        <th>Returner</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.all_shipped_returned.each do |order| %>
        <tr>
          <td><%= order.name %></td>
          <td><%= order.order_amt %></td>
          <td><%= order.shipping_amt %></td>
          <td><%= order.final_price %></td>
          <td><%= order.order_datetime.strftime("%A-%m-%Y %H:%M") %></td>
          <td><%= order.address %></td>
          <td><%= order.address2 %></td>
          <td><%= order.city %></td>
          <td><%= order.zipcode %></td>
          <td><span class="label label-warning"><%= User.find(order.shipper_id).name if order.shipper_id %></span></td>
          <td><span class="label label-warning"><%= User.find(order.returner_id).name if order.returner_id %></span></td>

          <td><%= order.shipping_code %></td>
          <td><%= order.shipping_type %></td>

          <td><%= link_to 'Show', order, class: "btn btn-default" %></td>
          <td><%= link_to 'Edit', edit_order_path(order), class: "btn btn-default" %></td>
          <td><%= link_to 'Returned?', returned_order_path(order), class: "btn btn-primary", method: :put %></td>
          <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, cancelled_order_path(order), class: "btn btn-danger", method: :put %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% end %>


<% end %>